# Generated by Django 4.1.2 on 2022-10-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sumari', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sumari',
            name='text',
            field=models.CharField(max_length=1000),
        ),
    ]
