# Generated by Django 4.1.2 on 2022-10-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sumari', '0004_rename_tittle_sumari_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sumari',
            name='text',
        ),
        migrations.RemoveField(
            model_name='sumari',
            name='title',
        ),
        migrations.AddField(
            model_name='sumari',
            name='link',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sumari',
            name='resumo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
